"use strict";var l=require("electron"),g=process;process.once("loaded",()=>{let c=e=>{l.ipcRenderer?.send("preload-script-error",e?.message)};try{window.global=window,global.process=g,window.ipc=l.ipcRenderer}catch(e){c(e)}try{let e=window.process.argv.find(t=>t.startsWith("--fiddler-zoom-factor="));e&&l.webFrame.setZoomFactor(parseFloat(e.substring(22)))}catch(e){c(e)}try{let e=document.cookie}catch{return}if(document.cookie||(document.cookie="FiddlerTestCookie=true; path=/"),!document.cookie){let e="__fiddler_file_cookies__";try{let t=new Date().getTime(),o=JSON.parse(localStorage.getItem(e)||"[]");for(let r=o.length-1;r>=0;r--){let i=o[r]?.key||"";if(!i.startsWith("_g")&&i!=="ssid")o.splice(r,1);else{let s=o[r]?.cookie?.indexOf("xpires=")+7;if(s!==6&&s<o[r].cookie.length){let n=o[r].cookie.indexOf(";",s+1),a=o[r].cookie.substring(s,n===-1?void 0:n);a&&new Date(a).getTime()<t&&o.splice(r,1)}}}localStorage.setItem(e,JSON.stringify(o))}catch(t){c(t)}document.__defineGetter__("cookie",()=>{let t=[];try{t=JSON.parse(localStorage.getItem(e)||"[]")}catch(o){c(o)}return t?t.map(o=>o.key+"="+o.value).join("; "):""}),document.__defineSetter__("cookie",t=>{let r=(t.indexOf(";")?t.substring(0,t.indexOf(";")):t).trim().split("=");if(r.length!==2)return;let i=r[0].trim(),s=r[1].trim();if(i?.startsWith("WZRK_"))return;let n=[];try{n=JSON.parse(localStorage.getItem(e)||"[]")}catch(d){c(d)}let a=n.findIndex(d=>d&&d.key===i);a!==-1?n[a]={key:i,value:s,cookie:t}:n.push({key:i,value:s,cookie:t}),localStorage.setItem(e,JSON.stringify(n))})}});
(async () => {
  console.info("-------Translation----------");

  const trnaslationData = {
    zhCn: {
      simple: {
        'Report an Issue': '报告问题',
        'Feedback': '反馈',
        'Contact Support': '联系支持',
        'Help': '帮助',
        'Settings': '设置',
        'Actual Size': '实际大小',
        'Zoom In': '放大',
        'Zoom Out': '缩小',
        'Tools': '工具',
        'Certificate': '证书',
        'AutoSave': '自动保存',
        'Decode value': '解码值',
        'Advanced Replay': '高级重放',
        'Release Notes': '发行说明',
        'Check for Updates': '检查更新',
        'Forums': '论坛',
        'Documentation': '文档',
        'About': '关于',
        'Privacy Center': '隐私中心',
        'Keyboard Shortcuts': '键盘快捷键',
        'Open Application Logs Folder': '打开应用日志文件夹',
        'Trust CA Certificate': '信任CA证书',
        'in the User Store': '在用户存储中',
        'in the Machine Store': '在机器存储中',
        'Export CA Certificate': '导出CA证书',
        'Reset CA Certificate': '重置CA证书',
        'Remove CA Certificate': '移除CA证书',
        'Capture HTTPS traffic': '捕获HTTPS流量',
        'Ignore Server Certificate Errors (Unsafe)': '忽略服务器证书错误（不安全）',
        'View': '视图',
        'Select Previous Tab': '选择上一个标签页',
        'Select Next Tab': '选择下一个标签页',
        'Reset': '重置',
        'Remove': '移除',
        'Buy Now': '立即购买',
        'Capture and Inspect Traffic': '捕获和检查流量',
        'Set System Proxy': '设置系统代理',
        'Open Clean Browser': '打开纯净浏览器',
        'Open Terminal': '打开终端',
        'Connect Remote Devices': '连接远程设备',
        'Modify and Filter Traffic': '修改和过滤流量',
        'Create Rules': '创建规则',
        'Create Filters': '创建过滤器',
        'API Testing': 'API 测试',
        'Compose API Requests': '构建API请求',
        'Import from Fiddler Classic': '从Fiddler Classic导入',
        'Import Fiddler Classic Settings': '导入Fiddler Classic设置',
        'Snapshots': '快照',
        'Shared with Me': '与我共享',
        'My Snapshots': '我的快照',
        'AutoSaved': '自动保存',
        'Live Traffic': '实时流量',
        'Filters': '过滤器',
        ' Saved Filters ': ' 已保存的过滤器 ',
        ' Clear ': ' 清除 ',
        'System Proxy': '系统代理',
        'Browser': '浏览器',
        'Terminal': '终端',
        ' Save ': '保存',
        ' AutoSave ': '自动保存',
        ' Share ': '分享',
        ' Columns ': '显示列',
        'Overview': '概览',
        'Inspectors': '检查器',
        'Rules': '规则',
        'Session Details': '会话详情',
        'Protocol: ': '协议: ',
        'Session State: ': '会话状态: ',
        'Session ID: ': '会话ID: ',
        'Add Rule': '添加规则',
        'Add Group': '添加组',
        'Promote': '提升',
        'Demote': '降级',
        'Duplicate': '复制',
        'Delete': '删除',
        'Requests': '请求',
        'Composer': '构建器',
        'Execute': '执行',
        'Save': '保存',
        'Show autogenerated headers': '显示自动生成的头部',
        ' Key ': ' 名称 ',
        ' Value ': ' 值 ',
        ' Description ': ' 描述 ',
        'Description': '描述',
        'Response': '响应',
        'Preview': '预览',
        'Name': '名称',
        'Name ': '名称 ',
        'Rename': '重命名',
        'New Folder': '新建文件夹',
        'Share': '分享',
        'Duplicate Collection': '复制集合',
        'Enter a name to save as a new filter': '输入名称以保存为新过滤器',
        'Save the current filter': '保存当前过滤器',
        'Duplicate the current filter': '复制当前过滤器',
        'Revert Changes': '撤销更改',
        'Delete this filter forever?': '永久删除此过滤器？',
        'Clear all conditions?': '清除所有条件？',
        'Filter name': '过滤器名称',
        'Name is required!': '名称是必填项！',
        'Yes': '是',
        'No': '否',
        'Clear All Conditions': '清除所有条件',
        'Add Condition': '添加条件',
        'Contains': '包含',
        'Does not contain': '不包含',
        'Is equal to': '等于',
        'Is not equal to': '不等于',
        'Starts with': '以...开头',
        'Ends with': '以...结尾',
        'Is empty': '为空',
        'Is not empty': '不为空',
        'Regular expression': '正则表达式',
        'Close': '关闭',
        ' Apply ': ' 应用 '
      },
      regexp: {
        'Timings \\((.*?)\\)': '时序 ({0})',
        ' (\\d+) selected ': ' {0} 选中 '
      }
    }
  }
  // 用于切换语言时更新
  const node2keyword = new Map();
  let lang = "zhCn";
  let currentDict = trnaslationData[lang]

  /**
   *  TODO: 改成是否全英文判断
   * @param {*} str 
   * @returns 
   */
  const containsFullChinese = (str) => {
    // 匹配大多数汉字、繁体中文和部分中文标点
    const fullChineseRegex = /[\u4e00-\u9FFF\u3002\uff1b\uff0c\uff1a\u201c\u201d\uff08\uff09\u3001\uff1f\u300a\u300b\uff01\u3010\u3011\uffe5]/;
    return fullChineseRegex.test(str);
  }
  const getSingleNode = (node) => {
    // element get
    const eles = [node];
    const result = [];
    while (eles.length > 0) {
      const ele = eles.pop();
      if (!ele) continue;
      if (ele.hasChildNodes()) {
        for (let i = 0; i < ele.childNodes.length; i++) {
          const child = ele.childNodes[i];
          // 忽略image
          if (child.nodeName === "IMG") continue;
          // 忽略path
          if (child.nodeName === "path") continue;
          // 忽略svg
          if (child.nodeName === "svg") continue;
          // 忽略br
          if (child.nodeName === "BR") continue;
          // 忽略source
          if (child.nodeName === "SOURCE") continue;
          // 忽略rect
          if (child.nodeName === "rect") continue;
          // 忽略circle
          if (child.nodeName === "circle") continue;
          // 忽略script
          if (child.nodeName === "SCRIPT") continue;
          if (
            child.nodeType === Node.ELEMENT_NODE && child instanceof HTMLElement &&
            (child.className.includes("bili-video-card__image") || // 视频
              child.className === "info"
            )
          )
            continue;
          if (
            child.textContent && 
            (
              /^\d+:\d+$/.test(child.textContent)
              || /^\d+\.\d+\.\d+$/.test(child.textContent)
              || /^\d+ \/ \d+$/.test(child.textContent)
              || /^(\d+)$/.test(child.textContent)
            )
          ) continue
          eles.push(child);
          if (child instanceof HTMLElement) {
            const title = child.attributes.getNamedItem("title");
            if (title && title.textContent && title.textContent.length > 0) {
              result.push(title);
            }
            const placeholder = child.attributes.getNamedItem("placeholder");
            if (placeholder && placeholder.textContent && placeholder.textContent.length > 0) {
              result.push(placeholder);
            }
          }
        }
        continue;
      }
      // 单元素节点
      if (!ele.textContent || ele.textContent.length === 0) continue;
  
      if (!isNaN(Number(ele.textContent))) continue
      
      result.push(ele);
    } // end while
    return result;
  };
  /** @param {Node} node */
  const translate = (node) => {
    if (!node.textContent) return false
    // log.info('translate:', node.textContent);
    if (!currentDict) return false
    const key = node.textContent.trim()
    const langText = currentDict.simple[key]
    if (!langText) {
      for (const [reg, text] of Object.entries(currentDict.regexp)) {
        const regExp = new RegExp(reg, 'g')
        if (regExp.test(node.textContent)) {
          node.textContent = node.textContent.replace(regExp, (_ss, ...args) => {
            let t = text
            for (let i = 0; i < args.length; i++) {
              t = t.replace(`{${i}}`, args[i])
            }
            // log.info('reg translation:', t)
            return t
          })
          // log.info('reg trnslation result:', node.textContent)
          return true
        }
      }
      return false
    }
    // 使用replace，因为trim会把换行空格移除掉
    node.textContent = node.textContent.replace(key, langText)
    return true
  };
  window.switchLanguage = async (newLang) => {
    if (newLang === lang) return;
    document.body.setAttribute('lang', newLang)
    currentDict = trnaslationData[newLang]
    console.info("switchLanguage -> ", newLang);
    lang = newLang;
    for (const [node, keyword] of node2keyword.entries()) {
      const r = translate(node)
      if (!r) {
        node.textContent = keyword
      }
    }
  };

  const observer = new MutationObserver((mutations) => {
    // console.info('[load]: MutationObserver', mutations);
    mutations.forEach((mutation) => {
      if (mutation.type === "childList") {
        mutation.addedNodes.forEach((node) => {
          if (node.nodeType === Node.ELEMENT_NODE && node instanceof HTMLElement) {
          const list = getSingleNode(node)
          // log.info('list:', list)
          for (const item of list) {
            if (!item.textContent) continue
            if (!node2keyword.has(item)) {
              node2keyword.set(item, item.textContent);
            } else if (!containsFullChinese(item.textContent) && node2keyword.get(item) !== item.textContent) {
              node2keyword.set(item, item.textContent);
            }
            translate(item);
          }
        } else if (node.nodeType === Node.DOCUMENT_FRAGMENT_NODE && node instanceof ShadowRoot) {
          const list = getSingleNode(node)
          // log.info('list:', list)
          for (const item of list) {
            if (!item.textContent) continue
            if (!node2keyword.has(item)) {
              node2keyword.set(item, item.textContent);
            } else if (!containsFullChinese(item.textContent) && node2keyword.get(item) !== item.textContent) {
              node2keyword.set(item, item.textContent);
            }
            translate(item);
          }
          // 设置part，使css生效
          for (let i=0; i < node.childNodes.length; i++) {
            const child = node.childNodes[i]
            if (!child) continue
            if (child.nodeType === Node.ELEMENT_NODE && child instanceof HTMLElement && child.id) {
              child.setAttribute('part', child.id)
            }
          }
          // 每层都设置part导出
          node.host?.setAttribute('exportparts', 'options')
        } else if (node.nodeType === Node.TEXT_NODE) {
            translate(node);
          }
        });
      }
    });
  });
  document.addEventListener('keyup', async (e) => {
    // Ctrl + T
    if (e.ctrlKey && (e.key === 't' || e.key === 'T')) {
      console.info('按下 Ctrl + T 键')
      document.getElementById('languageChangePanel')?.remove()
      // const lang = await window.requestBackground('getStorage', {key: 'lang'}) || 'zh_CN'
      const languageChangePanel = document.createElement('div')
      languageChangePanel.id = 'languageChangePanel'
      languageChangePanel.style.position = 'fixed'
      languageChangePanel.style.bottom = '10px'
      languageChangePanel.style.left = '10px'
      languageChangePanel.style.backgroundColor = 'white'
      languageChangePanel.style.padding = '10px'
      languageChangePanel.style.border = '1px solid black'
      languageChangePanel.style.zIndex = '10000'
      languageChangePanel.innerHTML = `
        <h3>Language:</h3>
        <select id="languageSelect">
          <option value="zhCn" ${lang === 'zhCn' ? 'selected' : ''}>简体中文</option>
          <option value="en" ${lang === 'en' ? 'selected' : ''}>English</option>
        </select>
        <button id="languageChangeButton">OK</button>
        <button id="closeLanguageChangePanel">X</button>
      `
      document.body.appendChild(languageChangePanel)
      languageChangePanel.querySelector('#languageChangeButton').addEventListener('click', async () => {
        const selectedLanguage = languageChangePanel.querySelector('#languageSelect').value
        console.info('选择的语言:', selectedLanguage)
        // await window.requestBackground('setStorage', {key: 'lang', value: selectedLanguage})
        // window.biliBridgePc.callNativeSync('config/changeLanguage', selectedLanguage)
        switchLanguage(selectedLanguage)
        console.info('切换语言成功:', selectedLanguage)
      })
      languageChangePanel.querySelector('#closeLanguageChangePanel').addEventListener('click', () => {
        document.body.removeChild(languageChangePanel)
      })
    }
  })
  if (!document.body) {
    console.warn(
      "MutationObserver: document.body is not ready yet, waiting for it to be available."
    );
    document.addEventListener("DOMContentLoaded", () => {
      console.info(
        "MutationObserver: document.body is now ready, starting to observe."
      );
      observer.observe(document.body, {
        childList: true,
        subtree: true,
        attributes: false,
        characterData: true,
      });
    });
    return;
  }
  console.info(
    "MutationObserver: document.body is ready, starting to observe."
  );
  observer.observe(document.body, {
    childList: true,
    subtree: true,
    attributes: false,
  });
})();
